spring:
  application:
    name: ms-booking

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/flight-booking
    username: postgres
    password: password

  liquibase:
    change-log: classpath:db/changelog-master.yaml