spring:
  application:
    name: ms-booking

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:3333/postgres
    username: postgres
    password: emin563

  liquibase:
    change-log: classpath:db/changelog-master.yml